# Generated by Django 4.1.7 on 2023-03-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficflowprediction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='overload',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='overspeed',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='state',
            field=models.CharField(max_length=5),
        ),
    ]
